name: Publish demo
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          default: true

      - uses: actions-rs/install@v0.1
        with:
          crate: wasm-bindgen-cli
          version: latest
          use-tool-cache: true

      - run: ./scripts/build-demo-web.sh

      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: target/website
